app: vjepa
nodes: 16
tasks_per_node: 8
data:
  dataset_type: wkwDataset
  datasets:
    - path: /srv/projects/paper_l4
      topleft: [500, 500, 500]
      size: [2000, 2000, 2000]
  bounding_boxes: 
  batch_size: 8
  num_clips: 1 #number of clips per video to sample
  num_frames: 16 #
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 224
  patch_size: 16
  pin_mem: true
  num_workers: 12
data_aug:
  auto_augment: false
  motion_shift: false
  # random_resize_aspect_ratio:
  # - 0.75
  # - 1.35
  # random_resize_scale:
  # - 0.3
  # - 1.0
  reprob: 0.0
logging:
  folder: /srv/projects/unsupervised-vjepa/jepa_logs_2
  write_tag: jepa
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio: #aspect ratio of sampled masking blocks is between 0.75 and 1.5
      - 1.0
      - 1.0
    num_blocks: 1 #number of sampled masking blocks that will be unioned
    spatial_scale:  #how much % of the patch will one masking block cover
      - 0.15
      - 0.15
    temporal_scale: #How much % does the masking blocks cover over time axis
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_base
  pred_depth: 12
  pred_embed_dim: 384
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 300
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 300
  warmup: 40
  start_lr: 0.00002
  lr: 0.0000625
  final_lr: 1.0e-07
  ema:
  - 0.998
  - 1.0
